### ISSUE TITLE
My profile is not updating

### ISSUE THREAD

**Issue by doroxz** [Fortify-Labs/Fortify#323]
**Describe the bug**
My profile data is not updating, but i can see lobby anyway

https://fortify.gg/profile/1020752456?tab=matches

**Comment by ThomasK33** [comment]
Hey @doroxz, sorry for the late reply.

Your matches up to May 13th have all been recorded and are stored in the database.

As your profile is set to private by default, only you will be able to view your past matches and mmr history after logging in.

You can opt-in to make your profile public by clicking on the checkbox on the left.
After that everyone will be able to view your past match history and mmr progression.
![image](https://user-images.githubusercontent.com/2198487/119368217-08ef4b00-bcb3-11eb-80ad-feb45e2b5727.png)

The profile page should have also displayed an error message about the profile being private, but something broke.
Should be fixed by now.
